Changes and additions for firewalled-replit.com
replit/replit-docs-2 pull request #2
Opened 2022-05-26 22:24 UTC by qirtaiba

This adds a new docs section on Firewalled Replit.

2022-05-26 23:41 UTC, Bardia95 requested changes

2022-05-26 23:41 UTC, Bardia95 commented on docs/firewalled-replit/firewalled-replit-faq.md
> +_Read more about this change at [our blog post](https://blog.replit.com/computing-superpower-at-school). Also, see our [commitment to user safety.](https://docs.google.com/document/d/1rGjlPhRIFDYVkLk
can we change this link from a google doc to a markdown repl or a doc hosted on the docs site

2022-05-27 00:05 UTC, Bardia95 commented on docs/firewalled-replit/firewalled-replit-faq.md
> +_Read more about this change at [our blog post](https://blog.replit.com/computing-superpower-at-school). Also, see our [commitment to user safety.](https://docs.google.com/document/d/1rGjlPhRIFDYVkLk
thanks!

2022-05-27 20:47 UTC, qirtaiba reviewed
Fixed URL that pointed to a Google Doc

2022-05-27 20:48 UTC, qirtaiba commented
Please merge by May 31 @Bardia95. Thanks!

2022-05-27 21:49 UTC, Bardia95 commented
thanks! can merge now if you're ready

2022-05-27 22:49 UTC, merged